FROM node:22-bookworm-slim

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma
RUN npm run db:generate

COPY . .

EXPOSE 3000

CMD ["sh", "-c", "npm run db:generate && npm run db:deploy && npm run dev"]
